- typescript/scheduledTasks.ts
> Revert "ON-34618 # Changed enabled and actions to required"

- typescript/scheduledTasks.ts
> Revert "ON-34619 # Changed enabled and actions to required"

- typescript/submissions.d.ts
> Revert "ON-38188 # add externalId to BaseFormSubmissionPayment"

- typescript/environments.d.ts
> ON-39773 # Added new cloning and migration option for form google maps integration

- typescript/keys.d.ts
> ON-43459 # Added `NewSubmissionDataKey` type

- typescript/keys.d.ts
> ON-43508 # Added FormKeyAssociation type

- typescript/forms.d.ts
> ON-43434 # add autocompleteAttributes to _FormElementBase

- typescript/forms.d.ts
> ON-43562 # move autocompleteAttributes onto specific elements

- typescript/formsApps.d.ts
- typescript/integrations.d.ts
> ON-43674 # Added type of Recaptcha domains

- typescript/api.ts
> ON-43783 # Added `formsAppEnvironmentId` to `APIEnvironment` type

- typescript/forms.d.ts
> ON-43918 # Update types for conditional submission

- typescript/environments.d.ts
> ON-44226 # Added `isCloningScheduledTasks` to `NewFormsAppEnvironment`

- typescript/forms.d.ts
> ON-44403 # Added ReceiptAutoIncrementComponent

- typescript/organisations.d.ts
> ON-44433 # Added `maximumFormAutoIncrementReceiptComponents`

- typescript/integrations.d.ts
> ON-42745 # Nylas Integration Type

- typescript/scheduling.d.ts
- typescript/submissionEvents.d.ts
> ON-42786 # add NylasBooking type

- typescript/scheduling.d.ts
> ON-44622 # add schedulingRescheduleUrl to NewNylasBooking

- typescript/scheduling.d.ts
> ON-44664 # add NylasSchedulingConfiguration to SchedulingTypes

- typescript/organisations.d.ts
> ON-44672 # Add `clientIpAddress` to `NewAuditRecord`

- typescript/organisations.d.ts
> ON-44651 # Added SchedulingBookingSession audit type

- typescript/organisations.d.ts
> ON-44732 # Add `requireTeamMemberMfa` to `NewOrganisation`

- typescript/scheduling.d.ts
> ON-44793 # update id prop in NylasSchedulingConfiguration

- typescript/formsApps.d.ts
> ON-44743 # added `requireAppUserMfa` to `NewApprovalsApp`

- typescript/scheduling.d.ts
> ON-44868 Added grantId to NylasBooking

- typescript/organisations.d.ts
> Revert "ON-44732 # Add `requireTeamMemberMfa` to `NewOrganisation`"

- typescript/scheduling.d.ts
> ON-44902 # Added bookingId to NylasBooking

- typescript/approvals.d.ts
> ON-44770 # Added concurrent step types

- typescript/formsApps.d.ts
> ON-44858 # added `isAppUserMfaRequired` to `FormsAppConfiguration`

- typescript/organisations.d.ts
> ON-44825 # Audit type `ApprovalFormsAppMfaRequirement`

- typescript/approvals.d.ts
> ON-44953 # Added status to approvals to cater for an approval not longer requiring any actioning

- typescript/approvals.d.ts
> Revert "ON-44953 # Added status to approvals to cater for an approval not longer requiring any actioning"

- typescript/formsApps.d.ts
> ON-44969 # add cachingStrategy to FormsAppConfiguration

- typescript/formsApps.d.ts
> ON-44752 # add `requireAppUserMfa` to `NewFormStoreApp`

- typescript/formsApps.d.ts
> ON-45046 # add cachingStrategies to NewFormsApp

- typescript/forms.d.ts
> ON-45072 # `disableAutosaveData` to `NewForm`

- typescript/forms.d.ts
> ON-45052 # Add image url to `DynamicChoiceElementOption`

- typescript/environments.d.ts
> ON-45113 # Disable autosave clone/migration types

- typescript/integrations.d.ts
- typescript/submissionEvents.d.ts
> ON-45487 # Removed legacy nylas types

- typescript/environments.d.ts
- typescript/formsApps.d.ts
> ON-45486 # Added styles to FormsAppEnvironment

- typescript/environments.d.ts
- typescript/formsApps.d.ts
- typescript/organisations.d.ts
> ON-45629 # Added FormsAppEnvironment sending address

- typescript/environments.d.ts
- typescript/formsApps.d.ts
> ON-45682 # Added `FormsAppEnvironmentSendingAddressResponse` type

- typescript/environments.d.ts
- typescript/formsApps.d.ts
- typescript/integrations.d.ts
- typescript/misc.d.ts
- typescript/submissionEvents.d.ts
- typescript/submissions.d.ts
> ON-45647 # Changed formsAppId to be optional for submissions

- typescript/environments.d.ts
> ON-45736 # Removed sendingAddress from BaseFormsAppEnvironment

- typescript/environments.d.ts
- typescript/forms.d.ts
- typescript/formsApps.d.ts
> ON-45790 # Added FormsAppEnvironmentConfigurationBase

- typescript/submissions.d.ts
> ON-45899 # Added scheduled task properties to _BaseFormStoreRecord

- typescript/forms.d.ts
> ON-45968 # Added archived prop to form

- typescript/forms.d.ts
> ON-46249 # add layout prop to RepeatableSetElement

- typescript/integrations.d.ts
- typescript/submissionEvents.d.ts
> ON-46638 # Added sharepoint integration and form workflow event

- typescript/submissionEvents.d.ts
> ON-46639 # type for SharepointCreateListItemSubmissionEvent

- typescript/submissionEvents.d.ts
> ON-46887 # Added flag to exclude attachments

- typescript/environments.d.ts
- typescript/forms.d.ts
- typescript/submissionEvents.d.ts
> ON-46912 # Added types for custom pdfs

- typescript/submissionEvents.d.ts
> ON-47012 # Removed pdfType property

- typescript/scheduling.d.ts
> ON-47013 # add NylasCalendar to scheduling types

- typescript/submissionEvents.d.ts
> ON-47081 # Added string array to supported mapping values

- typescript/submissionEvents.d.ts
> ON-47205 # Add `allowPDFDownload` to payment events

- typescript/submissionEvents.d.ts
> ON-47231 # Added SharepointResourceDefinitionBase

- typescript/forms.d.ts
- typescript/submissionEvents.d.ts
> ON-47259 # Move allowPDFDownload config for form level

- typescript/forms.d.ts
> ON-47261 # Remove new config

- typescript/organisations.d.ts
> ON-47460 # Added maximumFormCustomPDFs to Tier

- typescript/teamMembers.d.ts
> ON-47398 # Added isMfaRequired to Permission

- typescript/submissionEvents.d.ts
> ON-47529 # Added option to make Custom PDF Editable

- typescript/integrations.d.ts
- typescript/submissionEvents.d.ts
> OB-2229 # Civic Rec Integration + Workflow Event

- typescript/submissionEvents.d.ts
> OB-2326 # Added empty configuration to Civic Rec Complete checkout workflow event

- typescript/api-nsw/liquor.ts
- typescript/cdn.d.ts
- typescript/forms.d.ts
- typescript/geoscape/address-details.d.ts
- typescript/geoscape/addresses.d.ts
- typescript/point/address-details.d.ts
- typescript/point/addresses.d.ts
> OB-2372 # add SHAREPOINT_LIST to static option set type

- typescript/api-nsw/liquor.ts
- typescript/cdn.d.ts
- typescript/forms.d.ts
- typescript/geoscape/address-details.d.ts
- typescript/geoscape/addresses.d.ts
- typescript/point/address-details.d.ts
- typescript/point/addresses.d.ts
> Revert "OB-2372 # add SHAREPOINT_LIST to static option set type"

- .prettierignore
- typescript/cdn.d.ts
- typescript/forms.d.ts
> OB-2372 # make a new type of option set

- typescript/forms.d.ts
> OB-2386 # Added FormElementOptionSetEnvironmentSharePointListColumn

- typescript/forms.d.ts
> OB-2361 # Added isDisplayingAddressInformation to NSW Point address form element

- typescript/integrations.d.ts
> ob-2410 # Updated delete integration validation type

- typescript/forms.d.ts
> ob-2411 # Added sharepoint app id to form

- typescript/forms.d.ts
> OB-2469 # add requiresAuthorisation to NewFormElementOptionSetBase

- typescript/forms.d.ts
> AP-2480 # Removed options set authorisation properties

- typescript/integrations.d.ts
> AP-2513 # add secret to civicRec integration

- typescript/integrations.d.ts
> AP-2521 # update Integration generic union

- typescript/forms.d.ts
> AP-2518 # Removed FormElementOptionSetSearchParameters

- typescript/arcgis/index.d.ts
- typescript/forms.d.ts
> ON-47878 # added additional properties to ArcGISWebMap element type

- typescript/formsApps.d.ts
> AP-2540 # Added isAlwaysSubmittingViaPendingQueue

- typescript/formsApps.d.ts
> AP-2569 # Changed property name to alwaysSubmitViaPendingQueue

- typescript/arcgis/index.d.ts
- typescript/forms.d.ts
> ON-47888 # Make `webMapId` optional in `ArcGISWebMapElement`

- typescript/forms.d.ts
> ON-47896 # Add new properties to ArcGISWebMapElement

- typescript/forms.d.ts
> aap-2655 # Added form level prop for point v3 key

- typescript/forms.d.ts
> ON-47905 # Add `graphicTypes` to  `allowedDrawingWidgets`

- typescript/forms.d.ts
> ON-48075 # Add id to `graphicTypes`

- typescript/misc.d.ts
> AP-2810 # Added address and department details to user profile

- typescript/formsApps.d.ts
> ap-2876 # Added htmlTags to FormsAppConfiguration type

- typescript/formsApps.d.ts
> MS-173 # Add `googleAnalyticsTagId`

- typescript/formsApps.d.ts
> MS-183 # Add `googleAnalyticsTagId` to `FormsAppConfiguration`

- typescript/misc.d.ts
> MS-192 # Add new props to UserProfile

- typescript/environments.d.ts
> ap-3214 # Added faviconUrl

- typescript/forms.d.ts
> AP-3216 # Added requiresConfirmation to EmailElement

- typescript/environments.d.ts
- typescript/formsApps.d.ts
- typescript/organisations.d.ts
> MS-259 # Add `FormsAppEnvironmentHostnameConfiguration`

- typescript/organisations.d.ts
> MS-264 # Fix new audit types

- typescript/integrations.d.ts
> AP-3298 # Added OAuth auth type to trim integration environments

- typescript/environments.d.ts
> MS-269 # Move location of `customHostname`

- typescript/forms.d.ts
> AP-3350 # add isCurrency to NumberElement

- typescript/approvals.d.ts
> MS-304 # FlowInstanceNodeMeta

- typescript/approvals.d.ts
> MS-312 # Make dubmission approval fields partial in node meta type

- typescript/forms.d.ts
> MS-337 # Add description to `ArcGISWebMapElement.allowedDrawingTools`

- typescript/formsApps.d.ts
> AP-3489 # Added administratorGroupName and managerGroupName to forms apps

- typescript/organisations.d.ts
> ap-3525 # Added `environmentOrdering` to Organisation

- typescript/forms.d.ts
> MS-476 # Add `readOnly` to `FormFormElement`

- typescript/forms.d.ts
> AP-3851 # Added LookupButtonFormElement type

- typescript/arcgis/index.d.ts
> MS-455 # added `visible` property to ArcGISWebMapElementValue.layers

- typescript/submissions.d.ts
> AP-3930 # Added completionTimestamp to submissions

- typescript/forms.d.ts
> MS-576 # Add `measurementDimensionsEnabled` to `ArcGISWebMapElement`

- typescript/forms.d.ts
> AP-4191 # added FormElementOptionSetGoodToGoCustomField

- typescript/arcgis/index.d.ts
- typescript/forms.d.ts
> AP-4432 # Added snapshot image to ArcGISWebMapElementValue

- typescript/forms.d.ts
> AP-4455 # add autoSnapshotViews to ArcGISWebMapElement

- typescript/forms.d.ts
> AP-4467 # update ArcGISWebMapElement autoSnapshot types

- typescript/submissions.d.ts
> AP-4592 # Added pathname to FormSubmissionAttachment

- typescript/integrations.d.ts
> AP-4705 # Changed civica integration to support OAuth

- typescript/submissionEvents.d.ts
> AP-5017 # Added PaymentDisplayDetailKey

- typescript/forms.d.ts
> AP-5084 # Added docs to headingType

- typescript/forms.d.ts
> AP-5086 # Added docs to HTML form element defaultValue property

- typescript/scheduledTasks.ts
> AP-5325 # add sub groups to Task Groups

- typescript/scheduledTasks.ts
> ap-5327 # Split out `TaskGroupSubGroup` type
